services:
  backend:
    build:
      context: ./
      target: builder
    ports:
      - '8000:8000'
    restart: "no"
    volumes:
      - ./:/app
  frontend:
    build: ./ui
    ports:
      - "80:80"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

